# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Csega's blog
email: csega@mailbox.hu
description: > # this means to ignore newlines until "baseurl:"
  This is a Jekyll blog I started to get to know Jekyll better and
  document some interesting programming idea I ran into or just my thoughts
  about a topic. If I make a project, you can read about it also here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "csega.github.io" # the base hostname & protocol for your site
twitter_username: Csega2
github_username:  csega

# Build settings
markdown: kramdown
